### ISSUE TITLE
Add option to display video captions

### ISSUE THREAD

**Issue by CVE42-chicken** [gebruederheitz/wp-block-video-overlay#3]
See also https://github.com/gebruederheitz/fact24/issues/904

Extend the block with a new attribute `cc_lang_pref` (labelled by "Caption Language Preference").

Via [the options object of the `register()` function](https://github.com/gebruederheitz/wp-block-video-overlay/blob/25b4c27a64bbc50e6c9cbe6bf40c6bbbc60fc2a3/src/editor/index.js#L14) we can pass an array of languages (`language-slug -> language label`, e.g. `[{value: "de", label: "Deutsch"}, {value: "en", label: "English"}]`) in an optional setting.

If an array of languages is defined, we can render a `<select>` field, otherwise a simple text input can be used to specify the language value.

A block deprecation will probably not be required, but I'd say it's cleaner to create one anyway.

**Comment by koetzsch** [comment]
- Auswahlliste der von Polylang eingerichteten Sprache
- Fallback, wenn keine Sprache ausgewählt wurde
- Datei bspw.: src/editor/index.js
- CamelCase
- VideoEditSettings verwenden (gucken unter VideoSearch)
